### ISSUE TITLE
CORAL-2 Test suite integration

### ISSUE THREAD

**Issue by josemonsalve2** [OpenMP-Validation-and-Verification/OpenMP_VV#60]
Include these tests 

> Jose, Kyle, Sunita, and Oscar,
> 
> I recently read about work in the CORAL-2 procurement using the SOLLVE OpenMP test suite to demonstrate compiler functionality.  This is clearly very valuable work and having a comprehensive test suite is very important to us.
> 
> In the course of preparing for Sierra at LLNL, Aaron Black identified a large number of bugs in XLF’s OpenMP offload support.  We have released the collection of reproducers as open source.  It can be found here:  https://github.com/LLNL/FGPU/
> 
> Would you be interested in reviewing our collection to find examples that would be good additions to the SOLLVE suite?
> 
> Thanks,
> 
> Dave

Test suggestions to review from FGPU (tests that are out of scope are removed from the list):

- [x] array_property_issues
- [x] declare_target
- [ ] first_private_clause_not_working
- [x] map_derived_type
- [ ] omp_assumed_shape_array_failure
- [ ] omp_parallel
- [ ] omp_parallel_barrier
- [ ] omp_privatizer_bug
- [ ] target_enter_data_map_failure
- [x] target_map
- [ ] target_unstructured_data
- [x] teams
- [ ] https://github.com/LLNL/FGPU/tree/master/examples/array_slices

**Comment by aaroncblack** [comment]
@josemonsalve2 - can you also add the omp map operation support on FORTRAN array slices at:
https://github.com/LLNL/FGPU/tree/master/examples/array_slices
Thanks

**Comment by josemonsalve2** [comment]
Thanks @aaroncblack ! I have added the link to the list

**Comment by spophale** [comment]
All positive feature tests have been added. Not covering negative testing at this point.
